FROM ubuntu:20.04
RUN apt-get update && apt-get install -y at build-essential pip locales git vim wget net-tools bzip2 procps apt-utils htop xterm && apt-get clean && locale-gen en_US.UTF-8
ENV TERM=xterm
VOLUME /data
WORKDIR /data
