FROM ghcr.io/matsubarai/lab502-server-guide/vitis:main
WORKDIR /
RUN git clone https://github.com/rogersce/cnpy.git && \
    apt-get update && apt-get install -y cmake googletest && apt-get clean && \
    cd cnpy && mkdir build && \
    cd build && cmake .. && \
    make && make install && \
    cd ../.. && rm -rf cnpy
WORKDIR /data
